### ISSUE TITLE
Fix index matching

### ISSUE THREAD

**Issue by mtdemers** [mtdemers/mkjson#1]
Find a better way to find the index of a certain value in the process loop. Currently, if a csv is from a document with identical values in different columns it may not assign them to the correct key.

**Comment by karuvally** [comment]
does the system take into account the headers in a CSV file?

**Comment by mtdemers** [comment]
Right now it's pulling out the first row and assumes those are the headers. It will break (create an invalid json) if there are rows below it with more entries than the first row, and also if any of the contents have commas in them.

**Comment by mtdemers** [comment]
Ok, I decided to pop out the line as it was being processed. That way it removes the issue with index matching, since it will only be scanning through a single line at a time. Should be good now.
